name: liverary
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ:-Asia/Seoul}
    ports:
      - "127.0.0.1:3307:3306" # 대부분 local에도 mysql 서버가 있어서
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - appnet

  kms:
    image: kurento/kurento-media-server:latest
    container_name: kms
    restart: unless-stopped
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      TZ: ${TZ:-Asia/Seoul}
      KMS_STUN_IP: ${KMS_SERVER_NAME}
      KMS_STUN_PORT: ${KMS_SERVER_PORT}
      KMS_TURN_URL: ${KMS_TURN_USER}:${KMS_TURN_PASSWORD}@${KMS_SERVER_NAME}:${KMS_SERVER_PORT}?transport=udp
    networks:
      - appnet
    labels: # 스프링 시작할 때 준비될 필요 x
      org.springframework.boot.readiness-check.tcp.disable: "true"

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    restart: unless-stopped
    ports:
      - "127.0.0.1:3478:3478/tcp"
      - "127.0.0.1:3478:3478/udp"
      - "127.0.0.1:5349:5349/tcp"
      - "127.0.0.1:5349:5349/udp"
      - "49160-49200:49160-49200/udp"
    environment:
      TZ: ${TZ:-Asia/Seoul}
    volumes:
      - ./.coturn/turnserver.conf:/etc/turnserver.conf:ro
    command: ["-c", "/etc/turnserver.conf"]
    networks:
      - appnet
    labels: # 스프링 시작할 때 준비될 필요 x
      org.springframework.boot.readiness-check.tcp.disable: "true"

networks:
  appnet:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
