import bookConcertImg from '@/assets/maps/book_concert_floor.png';
import booktalkFloorImg from '@/assets/maps/booktalk_floor.png';
import conferenceFloorImg from '@/assets/maps/conference_floor.png';
import lobbyImg from '@/assets/maps/lobby_floor.png';
import myRoomImg from '@/assets/maps/my_room.png';
import readingFloorImg from '@/assets/maps/reading_floor.png';

import type { FloorType, MapConfig } from '@/types/map.types';

export const MAP_DATA: Record<FloorType, MapConfig> = {
  lobby: {
    floorId: '11111111-1111-1111-1111-111111111111',
    name: '도서관 로비',
    img: lobbyImg,
    zones: [
      {
        id: 'lobby-board-left',
        label: '왼쪽 게시판',
        x: 0.715,
        y: 0.135,
        width: 0.068,
        height: 0.12,
        trigger: 'interact',
        action: {
          type: 'moveConfirm',
          title: '장소 이동',
          message: '내 서재로 이동하시겠습니까?',
          targetFloor: 'myRoom',
        },
      },
      {
        id: 'lobby-board-right',
        label: '오른쪽 게시판',
        x: 0.815,
        y: 0.135,
        width: 0.068,
        height: 0.12,
        trigger: 'interact',
        action: {
          type: 'moveConfirm',
          title: '장소 이동',
          message: '내 서재로 이동하시겠습니까?',
          targetFloor: 'myRoom',
        },
      },
      {
        id: 'lobby-elevator',
        label: '로비층 엘레베이터',
        x: 0.350,
        y: 0.125,
        width: 0.040,
        height: 0.075,
        trigger: 'interact',
        action: {
          type: 'openModal',
          modalType: 'elevator',
        },
      },
      {
        id: 'lobby-board-center',
        label: '중앙 게시판',
        x: 0.465,
        y: 0.230,
        width: 0.103,
        height: 0.085,
        trigger: 'interact',
        action: {
          type: 'moveConfirm',
          title: '장소 이동',
          message: '내 서재로 이동하시겠습니까?',
          targetFloor: 'myRoom',
        },
      },
    ],
  },
  readingFloor: {
    floorId: '22222222-2222-2222-2222-222222222222',
    name: '독서실',
    img: readingFloorImg,
    zones: [
      {
        id: 'reading-elevator',
        label: '독서실 엘레베이터',
        x: 0.350,
        y: 0.125,
        width: 0.040,
        height: 0.075,
        trigger: 'interact',
        action: {
          type: 'openModal',
          modalType: 'elevator',
        },
      },
      {
        id: 'reading-board-center',
        label: '독서실 중앙 게시판',
        x: 0.465,
        y: 0.230,
        width: 0.103,
        height: 0.085,
        trigger: 'interact',
        action: {
          type: 'moveConfirm',
          title: '장소 이동',
          message: '내 서재로 이동하시겠습니까?',
          targetFloor: 'myRoom',
        },
      },
    ],
  },
  conferenceFloor: {
    floorId: '55555555-5555-5555-5555-555555555555',
    name: '회의실',
    img: conferenceFloorImg,
  },
  bookTalkFloor: {
    floorId: '33333333-3333-3333-3333-333333333333',
    name: '독서 모임 공간',
    img: booktalkFloorImg,
    zones: [
      {
        id: 'room-1',
        label: '왼쪽 상단 룸',
        x: 0.025,
        y: 0.03,
        width: 0.310,
        height: 0.460,
        trigger: ['enter', 'exit'],
        enterAction: {
          type: 'confirmReposition',
          title: '장소 이동',
          message: '입장하시겠습니까?',
          confirmPosition: 'zoneCenter',
          cancelPosition: 'zoneFrontBelow',
        },
        exitAction: {
          type: 'confirmReposition',
          title: '장소 이동',
          message: '퇴장하시겠습니까?',
          confirmPosition: 'zoneFrontBelow',
          cancelPosition: 'zoneCenter',
        },
      },
      {
        id: 'room-2',
        label: '오른쪽 상단 룸',
        x: 0.665,
        y: 0.03,
        width: 0.310,
        height: 0.460,
        trigger: ['enter', 'exit'],
        enterAction: {
          type: 'confirmReposition',
          title: '장소 이동',
          message: '입장하시겠습니까?',
          confirmPosition: 'zoneCenter',
          cancelPosition: 'zoneFrontBelow',
        },
        exitAction: {
          type: 'confirmReposition',
          title: '장소 이동',
          message: '퇴장하시겠습니까?',
          confirmPosition: 'zoneFrontBelow',
          cancelPosition: 'zoneCenter',
        },
      },
      {
        id: 'room-3',
        label: '왼쪽 하단 룸',
        x: 0.025,
        y: 0.6,
        width: 0.310,
        height: 0.360,
        trigger: ['enter', 'exit'],
        enterAction: {
          type: 'confirmReposition',
          title: '장소 이동',
          message: '입장하시겠습니까?',
          confirmPosition: 'zoneCenter',
          cancelPosition: 'zoneFrontAbove',
        },
        exitAction: {
          type: 'confirmReposition',
          title: '장소 이동',
          message: '퇴장하시겠습니까?',
          confirmPosition: 'zoneFrontAbove',
          cancelPosition: 'zoneCenter',
        },
      },
      {
        id: 'room-4',
        label: '오른쪽 하단 룸',
        x: 0.665,
        y: 0.6,
        width: 0.310,
        height: 0.360,
        trigger: ['enter', 'exit'],
        enterAction: {
          type: 'confirmReposition',
          title: '장소 이동',
          message: '입장하시겠습니까?',
          confirmPosition: 'zoneCenter',
          cancelPosition: 'zoneFrontAbove',
        },
        exitAction: {
          type: 'confirmReposition',
          title: '장소 이동',
          message: '퇴장하시겠습니까?',
          confirmPosition: 'zoneFrontAbove',
          cancelPosition: 'zoneCenter',
        },
      },
      {
        id: 'talk-elevator',
        label: '독서 모임 공간 엘레베이터',
        x: 0.350,
        y: 0.125,
        width: 0.040,
        height: 0.075,
        trigger: 'interact',
        action: {
          type: 'openModal',
          modalType: 'elevator',
        },
      },
      {
        id: 'talk-board-center',
        label: '독서 모임 공간 중앙 게시판',
        x: 0.465,
        y: 0.080,
        width: 0.103,
        height: 0.085,
        trigger: 'interact',
        action: {
          type: 'moveConfirm',
          title: '장소 이동',
          message: '내 서재로 이동하시겠습니까?',
          targetFloor: 'myRoom',
        },
      },
    ],
  },
  bookConcert: {
    floorId: '44444444-4444-4444-4444-444444444444',
    name: '북 콘서트 홀',
    img: bookConcertImg,
    zones: [
      {
        id: 'concert-whiteboard',
        label: '북 콘서트 빔 프로젝트',
        x: 0.440,
        y: 0.070,
        width: 0.120,
        height: 0.085,
        trigger: 'interact',
        action: {
          type: 'moveConfirm',
          title: '장소 이동',
          message: '내 서재로 이동하시겠습니까?',
          targetFloor: 'myRoom',
        },
      },
      {
        id: 'concert-exit',
        label: '콘서트 퇴장 - 엘레베이터',
        x: 0.000,
        y: 0.800,
        width: 1.0,
        height: 0.200,
        trigger: 'interact',
        action: {
          type: 'openModal',
          modalType: 'elevator',
        },
      },
    ],
  },
  myRoom: {
    floorId: '00000000-0000-0000-0000-000000000000',
    name: '내 서재',
    img: myRoomImg,
    zones: [
      {
        id: 'myRoom-bookshelf-left',
        label: '왼쪽 책장',
        x: 0.005,
        y: 0.070,
        width: 0.155,
        height: 0.40,
        trigger: 'interact',
        action: {
          type: 'moveConfirm',
          title: '장소 이동',
          message: '내 서재로 이동하시겠습니까?',
          targetFloor: 'myRoom',
        },
      },
      {
        id: 'myRoom-bookshelf-right',
        label: '오른쪽 책장',
        x: 0.840,
        y: 0.070,
        width: 0.155,
        height: 0.40,
        trigger: 'interact',
        action: {
          type: 'moveConfirm',
          title: '장소 이동',
          message: '내 서재로 이동하시겠습니까?',
          targetFloor: 'myRoom',
        },
      },
    ],
  },
};
