export const manifest = {
  bundles: [
    {
      name: 'character-parts',
      assets: [
        { alias: 'mbody', src: '/assets/characters/basic_male.png' },
        { alias: 'fbody', src: '/assets/characters/basic_female.png' },
        { alias: 'sit', src: '/assets/characters/basic_sit.png' },
        { alias: 'longhair', src: '/assets/characters/long_hair.png' },
        { alias: 'shorthair', src: '/assets/characters/short_hair.png' },
        { alias: 'shirt', src: '/assets/characters/basic_shirts.png' },
        { alias: 'pants', src: '/assets/characters/basic_pants.png' },
        { alias: 'sithair', src: '/assets/characters/basic_sit_hair.png' },
        { alias: 'sitshirts', src: '/assets/characters/basic_sit_shirt.png' },
        { alias: 'sitpants', src: '/assets/characters/basic_sit_pant.png' },
      ],
    },
    {
      name: 'maps',
      assets: [
        { alias: 'myRoom', src: '/assets/maps/my_room.png' },
        { alias: 'bookConcert', src: '/assets/maps/book_concert_floor.png' },
        { alias: 'bookConcertTmj', src: '/assets/maps/book_concert.tmj' },
        { alias: 'bookTalkBasic', src: '/assets/maps/book_talk_floor.png' },
        {
          alias: 'bookTalkScience',
          src: '/assets/maps/book_talk_floor_science.png',
        },
        {
          alias: 'bookTalkComic',
          src: '/assets/maps/book_talk_floor_comic.png',
        },
        { alias: 'bookTalkTmj', src: '/assets/maps/book_talk_floor.tmj' },
        { alias: 'conference', src: '/assets/maps/conference_floor.png' },
        { alias: 'conferenceTmj', src: '/assets/maps/conference_floor.tmj' },
        { alias: 'lobby', src: '/assets/maps/lobby.png' },
        { alias: 'lobbyTmj', src: '/assets/maps/lobby.tmj' },
        { alias: 'readingFloor', src: '/assets/maps/reading_floor.png' },
        { alias: 'readingFloorTmj', src: '/assets/maps/reading_floor.tmj' },
      ],
    },
    {
      name: 'sounds',
      assets: [
        { alias: 'romantic_1', src: '/assets/bgm/A_Stroll_Alone.mp3' },
        { alias: 'calm_1', src: '/assets/bgm/From_Here_on_In.mp3' },
        { alias: 'arabian_1', src: '/assets/bgm/Lace_Tablecloths.mp3' },
        { alias: 'rain_1', src: '/assets/bgm/Light_Rain.mp3' },
        { alias: 'romantic_2', src: '/assets/bgm/Parisian_Cafe.mp3' },
        { alias: 'calm_2', src: '/assets/bgm/Powdered_Waltz.mp3' },
        {
          alias: 'cafe_1',
          src: '/assets/bgm/The_Girl_from_Saint_Anne_des_Plaines.mp3',
        },
        { alias: 'calm_3', src: '/assets/bgm/calm_3.mp3' },
        { alias: 'calm_4', src: '/assets/bgm/calm_4.mp3' },
        { alias: 'calm_5', src: '/assets/bgm/calm_5.mp3' },
        { alias: 'fairy_1', src: '/assets/bgm/fairy_1.mp3' },
        { alias: 'fairy_2', src: '/assets/bgm/fairy_2.mp3' },
        { alias: 'fairy_3', src: '/assets/bgm/fairy_3.mp3' },
        { alias: 'fairy_4', src: '/assets/bgm/fairy_4.mp3' },
        { alias: 'fairy_5', src: '/assets/bgm/fairy_5.mp3' },
        { alias: 'fairy_6', src: '/assets/bgm/fairy_6.mp3' },
        { alias: 'alternative_1', src: '/assets/bgm/alternative_1.mp3' },
        { alias: 'sf_1', src: '/assets/bgm/sf_1.mp3' },
      ],
    },
  ],
};
